name: Build and deploy ASP.Net Core app to Azure Web App - StudentRegistration-WebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build the application
        run: dotnet build student-registration/StudentRegistrationWebsite --configuration Release

      - name: Publish the application
        run: dotnet publish student-registration/StudentRegistrationWebsite -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StudentRegistration-WebApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_STUDENTPROFILE }}
          package: ./publish
